__common: &common_build
  language: rust
  rust: stable
  cache: cargo
#  language: cpp

stages:
  - build
  - release

matrix:

  include:

    ############ Linux build ############################

    - name: Linux build
      stage: build

      <<: *common_build
      os: linux
      dist: xenial

      before_install:
        # Build Tundra from source & install
        - git clone --recursive https://github.com/deplinenoise/tundra.git
        - cd tundra
        - make
        - sudo make install
        - cd ..

        # Install cargo 'deb' subcommand
        # If the subcommand is already installed, uninstall first; this ensures that the latest version is used
        - if [[ -n `cargo install --list | grep "cargo-deb"` ]]; then cargo uninstall cargo-deb; fi
        - cargo install cargo-deb

      script:
        # Run build script
        - ./build-scripts/linux-build.sh ${TRAVIS_BUILD_NUMBER}
        # If successful, this will provide files in the deploy folder, ready for deployment

      deploy:
        skip_cleanup: true

        on:
          all_branches: true

        provider: s3
        access_key_id: AKIAT67P2JAB4XDBKTXN
        secret_access_key:
          secure: JmJkUPDMsrRDXeIquCR2zBJNCQxNXdDzTYbzCJQZj3lUk4T/CS+Yk3mxiKwhoYm0GHyv2EnYCsCtJDpElk29T3qan4aC1PWyxZgYjEB80JbpRQ4LaMguKO1YAH6dUfwXFUg/nnZALgUqLVxKqLdXHOzc/IY87AGldYR963c3tGx+p737NryI7v/abDW2ENOZq7W0UTNynDDt7geO0VbNy0grxTVAZuhg46M7GE5qoWjldHqRUYOzRROqo/fzyJD7ZAKa9fw1iB5v1CGSYjVm4TfxMuQLpeqJjz2GtWOcHi1cmwZVRSV1UXsBJwXGBoqR59Eb6f//rJu+mThwGclK2h/86ECQcZzwems3Y2OQX8B5jd31PlUKGIE3VrUnm87bwo8A4ixR8m7SnUsk/K/2ao5xj211zBWClBmAIYApVSZSgMqXb4GvN5ye5SIT5Jod+hfljEDSGC4HXEpPHpuq9d8LZ7GQx7OJb6NaAXmThL7eq3vbOW3FnYC4H9q+OqhizDzkYxkeb9dWw4mECp43FQykWpPN2N2ApdCUXKiCTjOGrSvfR6sAfyanv3TE8DTwWXLMwEMeNnCxUEkvuUIvPSO82tRM6/4LDkiAzk6p4jFsbFimzpCE8W1p1oth1iudc5K4XvEc1SARx4prCS/rrEFDaQlhY3VB8jWJ6Bejbsw=
        bucket: testrunner-68k-artifacts
        region: eu-west-1
        local-dir: deploy
        acl: public_read

    ############ Windows build ############################

    - name: Windows build
      stage: build

      <<: *common_build
      os: windows

      before_install:
        # Fetch Tundra installer
        - cmd.exe /C 'start /wait wget https://github.com/deplinenoise/tundra/releases/download/v2.09/Tundra-Setup.exe'
        # Run Tundra installer
        - cmd.exe /C 'start /wait Tundra-Setup.exe /S'
        # Add Tundra binary path to current install path (as the installer does not refresh the current shell's env vars)
        - PATH="$PATH:/c/Program Files/Tundra 2.0/bin"

        # Setup VC environment variables. We assume that VS 2017 is already installed on the machine.
        - source ./build-scripts/run_command_and_apply_environment_differences.sh "call build-scripts\\vcvars64_vs2017.bat"

        # Install cargo 'wix' subcommand
        # If the subcommand is already installed, uninstall first; this ensures that the latest version is used
        - if [[ -n `cargo install --list | grep "cargo-wix"` ]]; then cargo uninstall cargo-wix; fi
        - cargo install cargo-wix

        # Install WiX Toolset
        - powershell Install-WindowsFeature Net-Framework-Core
        - cinst -y wixtoolset

      script:

        # Allow invocation of PowerShell scripts
        - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'

        # Run build script
        - powershell build-scripts/windows-build.ps1 -BuildId "$TRAVIS_BUILD_NUMBER"
        # If successful, this will provide files in the deploy folder, ready for deployment

      deploy:
        skip_cleanup: true

        on:
          all_branches: true

        provider: s3
        access_key_id: AKIAT67P2JAB4XDBKTXN
        secret_access_key:
          secure: JmJkUPDMsrRDXeIquCR2zBJNCQxNXdDzTYbzCJQZj3lUk4T/CS+Yk3mxiKwhoYm0GHyv2EnYCsCtJDpElk29T3qan4aC1PWyxZgYjEB80JbpRQ4LaMguKO1YAH6dUfwXFUg/nnZALgUqLVxKqLdXHOzc/IY87AGldYR963c3tGx+p737NryI7v/abDW2ENOZq7W0UTNynDDt7geO0VbNy0grxTVAZuhg46M7GE5qoWjldHqRUYOzRROqo/fzyJD7ZAKa9fw1iB5v1CGSYjVm4TfxMuQLpeqJjz2GtWOcHi1cmwZVRSV1UXsBJwXGBoqR59Eb6f//rJu+mThwGclK2h/86ECQcZzwems3Y2OQX8B5jd31PlUKGIE3VrUnm87bwo8A4ixR8m7SnUsk/K/2ao5xj211zBWClBmAIYApVSZSgMqXb4GvN5ye5SIT5Jod+hfljEDSGC4HXEpPHpuq9d8LZ7GQx7OJb6NaAXmThL7eq3vbOW3FnYC4H9q+OqhizDzkYxkeb9dWw4mECp43FQykWpPN2N2ApdCUXKiCTjOGrSvfR6sAfyanv3TE8DTwWXLMwEMeNnCxUEkvuUIvPSO82tRM6/4LDkiAzk6p4jFsbFimzpCE8W1p1oth1iudc5K4XvEc1SARx4prCS/rrEFDaQlhY3VB8jWJ6Bejbsw=
        bucket: testrunner-68k-artifacts
        region: eu-west-1
        local-dir: deploy
        acl: public_read

    ############ Release ############################

    - name: Release
      stage: release

      language: shell
      os: linux
      dist: xenial

      if: (tag =~ /^release-/)

      env:
      - TESTRUNNER_68K_APT_UPLOADER_ACCESS_KEY_ID=AKIAT67P2JAB23KORCF2
      # TESTRUNNER_68K_APT_UPLOADER_SECRET_ACCESS_KEY
      - secure: UlACxbe+pOz/7CHIuwUa5DLKlqklst4kAonwsRt0E4LaBhQgGWgO8JTubPN7OKrt0aPYPa6bGofhYI75OvRy4Dp2YMuJC35vV7wEmvu8EN9hP9TYhk7ibCby0cQIw8luCsoS5I++aUp/g0CBjtTjf9pDUWa9i8RtyTzOCJ+KEU+s9EwiF67dFobuMkqBIRpgqiXmuR5E4iukhp/QnuAUhzhOSsdSgbG64B5ZT47YWWzjt80IvA1thADXqP07IElHgufCvphi0hlMPPaKsa6ylAjTrh6tc5xa1VjdOKjcIgWuaYMLr6J6gEtXWu3TV+i5pF/lq82AtbO3o7nZFxT8gB60hGUnu5qp4x4V9YVhoxUrWrB89P7ALFYX0S3fi6O79vo5kT93/KkYKKLFitQb6INk2xtntNv/4uniYzfPGdd0Jc5pweC+wbjdcBM/GFMiOCv5DlHBGd7vCmSRMf7GQNQNVTnemAa9pEwF0NySL1xwtZYhld8RyT2hRtgL/Nth1ZFZVV00jNpejFcZmaEfsG4e80N+iJSUm+8TwLdJXPfqKBo64WC6tApIp1N8ORWCe0iXmCJboJyrIkQqJInPV5t1xn+lYDBWa/8AxVUnkg8yfUv/Na2sVBLwAlxTm6roiPhJaALbedxSuYZ5xBwSbUAc5dYlHmsNlGXA0J/QCEg=

      before_install:
        - gem install deb-s3

      script:
        - wget https://testrunner-68k-artifacts.s3-eu-west-1.amazonaws.com/testrunner-68k-0.0.${TRAVIS_BUILD_NUMBER}-windows-binaries.zip
        - wget https://testrunner-68k-artifacts.s3-eu-west-1.amazonaws.com/testrunner-68k-0.0.${TRAVIS_BUILD_NUMBER}-x86_64.msi
        - wget https://testrunner-68k-artifacts.s3-eu-west-1.amazonaws.com/testrunner-68k_0.0.${TRAVIS_BUILD_NUMBER}_amd64.deb

        - deb-s3 upload --bucket=testrunner-68k-apt --s3-region=eu-west-1 --access-key-id=${TESTRUNNER_68K_APT_UPLOADER_ACCESS_KEY_ID} --secret-access-key=${TESTRUNNER_68K_APT_UPLOADER_SECRET_ACCESS_KEY} testrunner-68k_0.0.${TRAVIS_BUILD_NUMBER}_amd64.deb

      deploy:
        skip_cleanup: true

        provider: releases
        api_key:
          secure: WkMMCXx/t1LdcWkyOd59akBj8TCz0ahO3CCnqv14swsO8CrE0QEWQaEYl2bQBrsJ2pnj4Z8Zx/DUZQEaDVThd0lNm4tduJuZaOU4wc5Fm/hRYFDfC36+6CkQTplJXkRVq/Gwb4F/xH8pbHn8pU6JTrfi2Peq11setrX20XaxhBkuqu9KcPrPXNzgxT8hKIUSHCHqkeb1ynUJl5mvOVIolRxpw1jgYCctJvh3Qt/QZTyDoWKtM4IAr4GWPMmD+Wa1h+z2QyDiG9fjzuiGlmhDynU/HDd7AL5yfgw1l27YMy4hNhh26zVmFXkTK0mBODXsAnPO3PrP4JF4QsVygiDFJcmkQ8WjyH3EE0YhChwcOjVSuvqIF36M6X17cZkiULLMMY9QwNuLn8BVFumH8XL6cawq1GacmYkLs4VoQi8on8hE6F3PotwflQOa5TAg5BB/rnGYAZvpZmoZ8bVhpygnxVUvWZFE5VtDPpTOAo47k/gHKcxh6hDmFw/EJ58D3T2qc7MAEoz1t0UB+9NF8tP2xRQ+h47H3mda4e/kmWnkNw8RB1x1ZBk5oEwXAmKYjWXhE0rFbNJXySPPKPP3GwZvdBbtfOH6okryX1sLqEWp+p1Me8e0F4kdpb71XopN6E+pqxruccJBxdyR5ZuBhZMiazpuaV8B1kq68epgv7K8aog=
        prerelease: false
        file:
          - testrunner-68k-0.0.${TRAVIS_BUILD_NUMBER}-windows-binaries.zip
          - testrunner-68k-0.0.${TRAVIS_BUILD_NUMBER}-x86_64.msi
          - testrunner-68k_0.0.${TRAVIS_BUILD_NUMBER}_amd64.deb

        on:
          tags: true
