
__common: &common
  # language: rust
  # rust: stable
  # cache: cargo
  language: c

matrix:

  include:
  # - <<: *common
  #   os: linux
  #   dist: xenial
    
  #   script:
  #   # Build Tundra from source & install
  #   - git clone --recursive https://github.com/deplinenoise/tundra.git
  #   - cd tundra
  #   - make
  #   - sudo make install
  #   - cd ..

  #   # Build Musashi
  #   - tundra2

  #   # Run testrunner-68k tests
  #   - cargo test

  - <<: *common
    os: windows

    before_install:
    # Fetch Tundra installer
    - cmd.exe /C 'start /wait wget https://github.com/deplinenoise/tundra/releases/download/v2.09/Tundra-Setup.exe'
    # Run Tundra installer
    - cmd.exe /C 'start /wait Tundra-Setup.exe /S'
    # Add Tundra binary path to current install path (as the installer does not refresh the current shell's env vars)
    - path %path%;%programfiles%\\Tundra 2.0\\bin
    - echo %path%

    script:
    #- cmd.exe /C 'start /wait wget https://github.com/deplinenoise/tundra/releases/download/v2.09/Tundra-Setup.exe'
    #- cmd.exe /C 'echo %path%'
    #- cmd.exe /C 'start /wait Tundra-Setup.exe /S'
    #- cmd.exe /C 'echo %path%'

    # Build Musashi
    - tundra2

    # Run testrunner-68k tests
    - cargo test
