
__common: &common_build
  # language: rust
  # rust: stable
  # cache: cargo
  language: cpp

stages:
  - build
  - deploy

matrix:

  include:
#   - <<: *common_build
#     os: linux
#     dist: xenial

#     name: Linux build
#     stage: build

#     before_install:
#     # Build Tundra from source & install
#     - git clone --recursive https://github.com/deplinenoise/tundra.git
#     - cd tundra
#     - make
#     - sudo make install
#     - cd ..

#     script:

#     # Build Musashi
#     - tundra2

#     # Run testrunner-68k tests
# #    - cargo test

#   - <<: *common_build
#     os: windows

#     name: Windows build
#     stage: build

#     before_install:
#     # Fetch Tundra installer
#     - cmd.exe /C 'start /wait wget https://github.com/deplinenoise/tundra/releases/download/v2.09/Tundra-Setup.exe'
#     # Run Tundra installer
#     - cmd.exe /C 'start /wait Tundra-Setup.exe /S'
#     # Add Tundra binary path to current install path (as the installer does not refresh the current shell's env vars)
#     - PATH="$PATH:/c/Program Files/Tundra 2.0/bin"

#     script:

#     # Setup VC environment variables. We assume that VS 2017 is already installed on the machine.
#     # Then, build Musashi
#     - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && tundra2'

#     # Run testrunner-68k tests
# #    - cargo test

  - language: shell
    os: linux
    dist: xenial

    name: Deploy
    stage: deploy

    if: tag =~ /^release-/

    script:
    - zip -r testrunner-68k-source.zip . -x testrunner-68k-source.zip "target/*" ".git/*" "t2-output/*" ".tundra2.*"

    deploy:
      provider: releases
      api_key:
        secure: "Ggu3Un+OdejVPc1mcyatJG3jduwpsSXOlohI3pknXHftLUr8jyhNiVtopuxOmDo2uAbshgkOXDQAQFSF7aPA3p62hhum2wd0h6ayic23u75FXBYfjky3B5xtcbFGOTO4pK8m0qMYCgbaSBj4U8uUz2gGh7qQFN77+8yRmzpr+3WkRfu2UyeJjjGCizDu8l7hSwsajxoRqV8mQ9kskkbk76vkhWeUAYPmEtZhdy+NM2lhWSy9PR0LOwoiM5egLF4ECEsYcjp2ewKx4fG7hePU/7A5lFV2UVcT8Si27u4QCPbjNCULgYjsEuqcGsREW6Ta5+trM+F9OVUdLymsgOsGItmIjILv7CxOuKWxLGcHtpHnjImUfLH620Cno7CBWm/FuWjuRghwV+8cMaufWXFj484FPNpsvKShNklZyPtxDOuvwwaOXfeGGcr5yhKQsCt2l9tSV+hhPM84pslgccY8ORhcrRbaNME2S/igdsLODzO06tcRPVC9wyoc6wc8nCktx8V6EKfhsNoAuCiM7V6o3WCcOWraIxg7PQeZvXU8LdsuoKzfyi8YA7gXI/6wjU1wb/RGujOtwVelQDAi0X8/JuXIU2yQdpEk7FsvH3MtvS5JGtG9c2iFO9vASodsytvnSy5rQ3WTWCb065HuqYqjtpPNWn2PefdvEXiciiLlvfs="
      file:
        - testrunner-68k-source.zip

      on:
        tags: true
