
__common: &common
  language: rust
  rust: stable
  cache: cargo

matrix:

  include:
  - <<: *common
    os: linux
    dist: xenial
    
    script:
    # Build Tundra from source & install
    - git clone --recursive https://github.com/deplinenoise/tundra.git
    - cd tundra
    - make
    - sudo make install
    - cd ..

    # Build Musashi
    - tundra2

    # Run testrunner-68k tests
    - cargo test

  - <<: *common
    os: windows

    script:
    # Fetch Tundra installer, run installer
    - wget https://github.com/deplinenoise/tundra/releases/download/v2.09/Tundra-Setup.exe
    - cmd.exe /C 'start /wait Tundra-Setup.exe /S'

    # Build Musashi
    - tundra2

    # Run testrunner-68k tests
    - cargo test
