
__common: &common_build
  language: rust
  rust: stable
  cache: cargo
#  language: cpp

stages:
  - build
  - release

matrix:

  include:

    ############ Linux build ############################

    - name: Linux build
      stage: build

      <<: *common_build
      os: linux
      dist: xenial

      before_install:
        # Build Tundra from source & install
        - git clone --recursive https://github.com/deplinenoise/tundra.git
        - cd tundra
        - make
        - sudo make install
        - cd ..

      script:
        - ./build-scripts/linux-build.sh

      ### Placeholder deploy script ###
      # script:
      # - mkdir deploy
      # - echo "hello" > deploy/file2.txt

      # deploy:
      #   skip_cleanup: true

      #   on:
      #     all_branches: true

      #   provider: gcs
      #   access_key_id: GOOGFQGMVO2253Z7JKRE4A7F
      #   secret_access_key:
      #     secure: bc2efA16UqUVjL7VrvTn1hnNn+ProzTrRRUH1f24xbB6Le2h4OvB4Jt+cFr+QCtpqqzKbSFbkW0G3qHOOkRaqK9fPUwugKOaFcz/dlchalN5R2ajt6Be5Z8NiXp/Skb6PKSdMhAHnAjEvpXbjAcYxxOTswLZqljSIvXJqTIOKaJQHMxnzW8o6edc9tNdiqFeIlgsQzaojOV/RmoTWBcvfUUvhfT+zUJyQVty1l9GJacYAh8+85+UrRa/6XrpcIm8iuh87sOiGaoeZw14gp/0KjAW9hAzEClhH5OEzzaTyccUYeD+pTbjh2ste15hYbx3+Y98kmRfxuuvS/xNLfaD5bT3zguLWzIUiTkNqjv9pFU4tsl/Yfe8wcewIPzGxsSsvINTWnEETg7L71cWcfnj/Z3dvAeMwbqGZ7XQdIbYyMy0N7nsoHF3hxZTk9oCujlcq1rW55AaDNev7qCy1bMX0+jn8OGelaRCppcyjxS7oAd/ixCLfAAJHWT4ZYSLh5x2WvpgSzPL2RN+dNRYDXDmECF05vd8FpD3FdVQaNA6c/rTS+0Og/uLqhsDaA3sDRX1PDVFfYLcrGeD2GFcllh8aMTa55oQbuwhVDWOt8O8KZrMqWhoGurxULI2MaMK3d4thyfn9oSL6drNjSQi+MiMedr+0Gq4FGgfm179zOCIIYE=
      #   bucket: testrunner-68k-artifacts
      #   local-dir: deploy

    ############ Windows build ############################

    - name: Windows build
      stage: build

      <<: *common_build
      os: windows

      before_install:
        # Fetch Tundra installer
        - cmd.exe /C 'start /wait wget https://github.com/deplinenoise/tundra/releases/download/v2.09/Tundra-Setup.exe'
        # Run Tundra installer
        - cmd.exe /C 'start /wait Tundra-Setup.exe /S'
        # Add Tundra binary path to current install path (as the installer does not refresh the current shell's env vars)
        - PATH="$PATH:/c/Program Files/Tundra 2.0/bin"

        # Setup VC environment variables. We assume that VS 2017 is already installed on the machine.
        - source ./build-scripts/run_command_and_apply_environment_differences.sh "call build-scripts\\vcvars64_vs2017.bat"

      script:

        # Allow invocation of PowerShell scripts
        - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'

        # Run build script
        - powershell build-scripts/windows-build.ps1 -BuildId $TRAVIS_BUILD_NUMBER
        # If successful, this will provide deploy/testrunner-68k.exe, ready for deployment


      deploy:
        skip_cleanup: true

        on:
          all_branches: true

        provider: gcs
        access_key_id: GOOGFQGMVO2253Z7JKRE4A7F
        secret_access_key:
          secure: bc2efA16UqUVjL7VrvTn1hnNn+ProzTrRRUH1f24xbB6Le2h4OvB4Jt+cFr+QCtpqqzKbSFbkW0G3qHOOkRaqK9fPUwugKOaFcz/dlchalN5R2ajt6Be5Z8NiXp/Skb6PKSdMhAHnAjEvpXbjAcYxxOTswLZqljSIvXJqTIOKaJQHMxnzW8o6edc9tNdiqFeIlgsQzaojOV/RmoTWBcvfUUvhfT+zUJyQVty1l9GJacYAh8+85+UrRa/6XrpcIm8iuh87sOiGaoeZw14gp/0KjAW9hAzEClhH5OEzzaTyccUYeD+pTbjh2ste15hYbx3+Y98kmRfxuuvS/xNLfaD5bT3zguLWzIUiTkNqjv9pFU4tsl/Yfe8wcewIPzGxsSsvINTWnEETg7L71cWcfnj/Z3dvAeMwbqGZ7XQdIbYyMy0N7nsoHF3hxZTk9oCujlcq1rW55AaDNev7qCy1bMX0+jn8OGelaRCppcyjxS7oAd/ixCLfAAJHWT4ZYSLh5x2WvpgSzPL2RN+dNRYDXDmECF05vd8FpD3FdVQaNA6c/rTS+0Og/uLqhsDaA3sDRX1PDVFfYLcrGeD2GFcllh8aMTa55oQbuwhVDWOt8O8KZrMqWhoGurxULI2MaMK3d4thyfn9oSL6drNjSQi+MiMedr+0Gq4FGgfm179zOCIIYE=
        bucket: testrunner-68k-artifacts
        local-dir: deploy

    ############ Release ############################

    - name: Release
      stage: release

      language: shell
      os: linux
      dist: xenial

      if: (tag =~ /^release-/)

      script:
        - wget http://storage.googleapis.com/testrunner-68k-artifacts/testrunner-68k-${TRAVIS_BUILD_NUMBER}-windows-binaries.zip

      deploy:
        skip_cleanup: true

        provider: releases
        api_key:
          secure: WkMMCXx/t1LdcWkyOd59akBj8TCz0ahO3CCnqv14swsO8CrE0QEWQaEYl2bQBrsJ2pnj4Z8Zx/DUZQEaDVThd0lNm4tduJuZaOU4wc5Fm/hRYFDfC36+6CkQTplJXkRVq/Gwb4F/xH8pbHn8pU6JTrfi2Peq11setrX20XaxhBkuqu9KcPrPXNzgxT8hKIUSHCHqkeb1ynUJl5mvOVIolRxpw1jgYCctJvh3Qt/QZTyDoWKtM4IAr4GWPMmD+Wa1h+z2QyDiG9fjzuiGlmhDynU/HDd7AL5yfgw1l27YMy4hNhh26zVmFXkTK0mBODXsAnPO3PrP4JF4QsVygiDFJcmkQ8WjyH3EE0YhChwcOjVSuvqIF36M6X17cZkiULLMMY9QwNuLn8BVFumH8XL6cawq1GacmYkLs4VoQi8on8hE6F3PotwflQOa5TAg5BB/rnGYAZvpZmoZ8bVhpygnxVUvWZFE5VtDPpTOAo47k/gHKcxh6hDmFw/EJ58D3T2qc7MAEoz1t0UB+9NF8tP2xRQ+h47H3mda4e/kmWnkNw8RB1x1ZBk5oEwXAmKYjWXhE0rFbNJXySPPKPP3GwZvdBbtfOH6okryX1sLqEWp+p1Me8e0F4kdpb71XopN6E+pqxruccJBxdyR5ZuBhZMiazpuaV8B1kq68epgv7K8aog=
        prerelease: false
        file:
          - testrunner-68k-${TRAVIS_BUILD_NUMBER}-windows-binaries.zip

        on:
          tags: true
